-- what is the total revenue generated by male vs female customers?
select gender, SUM(purchase_amount_usd) as revenue
from customer
group by gender;

-- which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount_usd
from customer
where discount_applied = 'Yes' and purchase_amount_usd >= (select AVG(purchase_amount_usd)
 from customer);
 
 -- what are the top five products with the highest average review rating?
 SELECT item_purchased, ROUND(AVG(review_rating),2) as average_rating
 FROM customer group by item_purchased order by average_rating DESC limit 5;
 
 -- compare the average shipping amounts between standard and express shipping
 select avg(purchase_amount_usd), shipping_type from customer where shipping_type in 
 ('Standard', 'Express') group by shipping_type;
 
 /* do subscribed customer spend more? compare average spend and total revenue between 
 subscribers and non subscribers */
 select subscription_status,COUNT(customer_id) as "Number of customer",
 avg(purchase_amount_usd) as 'Average spending', 
 sum(purchase_amount_usd) as 'total_revenue'
 from customer group by subscription_status;
 
 
 -- which 5 products has the highest percentage of purchases with discounts applied?
 select item_purchased,
 SUM(CASE WHEN discount_applied = 'Yes' then 1 ELSE 0 END)/COUNT(*)*100 AS discount_rate
 from customer 
 group by item_purchased
 order by discount_rate DESC limit 5;
 
 -- segment customers into New, Returning and Loyal based on their total number of previous purchases
 -- and show the count of each segment
 with customer_type as (
 select customer_id, previous_purchases,
 CASE 
 WHEN previous_purchases = 1 THEN 'New'
 WHEN previous_purchases BETWEEN 2 and 10 THEN 'Returning'
 ELSE 'Loyal'
 END AS customer_segment
 FROM customer
 )
 select customer_segment, count(*) as 'number of customer'
 from customer_type
 group by customer_segment;
 
 -- what are the top 3 most purchased products within each category?
 WITH product_counts AS (
    SELECT
        category,
        item_purchased,
        COUNT(*) AS purchase_count
    FROM customer
    GROUP BY category, item_purchased
),
ranked_products AS (
    SELECT
        category,
        item_purchased,
        purchase_count,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY purchase_count DESC
        ) AS item_rank
    FROM product_counts
)
SELECT
    category,
    item_purchased,
    purchase_count
FROM ranked_products
WHERE item_rank <= 3
ORDER BY category, purchase_count DESC;
 
 
 -- are customers who are repeat buyers(more than 5 purchases) also likely to subscribe?
 select subscription_status, count(customer_id) as 'number of customer'
 from customer where previous_purchases > 5 group by subscription_status;
 
 -- what is the contribution of age group ?
 select age_group, sum(purchase_amount_usd) as 'revenue' from customer
 group by age_group order by revenue DESC;
 